name: ECO2
channels:
    - conda-forge
dependencies:
    - python>=3.10
    - loguru
    - rich
    - typer
    - cx_freeze
    - lxml
    # dev
    - pytest
    - pyink
    - isort
    - pylint
    - mypy
    - ruff
