name: ECO2
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - lxml
  - loguru
  - rich
  - typer
  - cx_freeze
  - pythonnet
  - rtoml
  # dev
  - pytest
  - pytest-cov
  - pylint
  - mypy
  - ruff
