name: ECO2
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.10
    - loguru
    - rich
    - click
    - cx_freeze
    # dev
    - pytest
    - pylint
    - yapf
    - toml
    - mypy
