[project]
name = 'ECO2'
version = '0.2.1'
requires-python = '>=3.11'

[tool.ruff]
preview = true
respect-gitignore = false
output-format = 'concise'

[tool.ruff.format]
preview = true
quote-style = 'single'
docstring-code-format = true

[tool.ruff.lint]
select = ['ALL']
ignore = [
    'ANN',    # flake8-annotations
    'COM',    # flake8-commas
    'CPY',    # flake8-copyright
    'D1',     # pydocstyle: D1*
    'FIX',    # flake8-fixme
    'INP',    # flake8-no-pep420
    'ISC001', # flake8-implicit-str-concat: single-line-implicit-string-concatenation
    'Q',      # flake8-quotes
    'S',      # flake8-bandit
    'SIM105', # flake8-simplify: suppressible-exception
    'T20',    # flake8-print
    'TD',     # flake8-todos
]

[tool.ruff.lint.pydocstyle]
convention = 'numpy'

[tool.pylint.messages_control]
confidence = ['HIGH', 'CONTROL_FLOW', 'INFERENCE']
enable = ['bad-inline-option', 'useless-suppression']
disable = ['R', 'C', 'fixme']

[tool.mypy]
disable_error_code = ['import-untyped', 'import', 'var-annotated']
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true

[tool.pytest.ini_options]
addopts = ['-v', '--cov=./']

[tool.coverage.run]
omit = ['ECO2/__main__.py', 'ECO2/cx_setup.py']

[tool.typos.default.extend-words]
henc = 'henc'
