[project]
name = 'ECO2'
version = '0.1.3'
requires-python = '>=3.11'

[tool.ruff]
select = ['ALL']
ignore = ['ANN', 'COM', 'D1', 'FIX', 'ISC001', 'Q', 'S101', 'T20', 'TD']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.ruff.lint.pydocstyle]
convention = 'numpy'

[tool.pylint.messages_control]
disable = [
    'fixme',
    'import-error',
    'invalid-name',
    'missing-class-docstring',
    'missing-function-docstring',
    'missing-module-docstring',
    'redefined-outer-name',
    'too-few-public-methods',
    'too-many-arguments',
    'trailing-whitespace',
    'unused-argument',
    'unused-import',
    'unused-variable',
    'wrong-import-order',
]

[tool.mypy]
disable_error_code = ['var-annotated', 'import']
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true

[tool.pytest.ini_options]
addopts = '-v'
